-- 127_event_update_materiality.sql
--
-- Material-change push filtering (notification matrix item 2 of 4).
--
-- Product decision (docs/feature-clarity/notifications.md, "Material event
-- changes"): push-worthy changes are date/time, location, cancellation, and
-- volunteer openings. (Price is intentionally out of scope — events have no
-- price field.) Title, description, and image changes are NOT material.
--
-- The `notify-event-update` Edge Function uses this flag to decide who gets a
-- PUSH: attending RSVPs always; considering RSVPs only when the update is
-- material. Everyone (attending + considering, minus per-event opt-outs from
-- migration 126) still receives the in-app bell notification.
--
-- System field-change rows (generated by notify_event_field_changes) are
-- material by definition — they only ever describe date/end_time/location/
-- coords/volunteer-openings changes. Manual organiser posts default to
-- is_material = false (push reaches attending only, like a soft broadcast).

alter table public.event_updates
  add column if not exists is_material boolean not null default false;

comment on column public.event_updates.is_material is
  'When true, this update is a push-worthy material change (date/time/location/volunteer openings). Considering RSVPs receive push only for material updates; attending RSVPs always do. Manual posts default false.';

-- Re-create the field-change trigger function to (a) also watch
-- volunteer_openings and (b) stamp is_material = TRUE on the synthetic row.
create or replace function public.notify_event_field_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  parts text[] := array[]::text[];
  msg   text;
begin
  -- Only care about published events. Status-change cancellations are
  -- handled by notify-event-cancelled.
  if coalesce(new.status, '') <> 'published' then
    return new;
  end if;

  if new.date is distinct from old.date then
    parts := array_append(parts, 'date');
  end if;
  if new.end_time is distinct from old.end_time then
    parts := array_append(parts, 'end time');
  end if;
  if new.location is distinct from old.location then
    parts := array_append(parts, 'venue');
  end if;
  if new.latitude is distinct from old.latitude
     or new.longitude is distinct from old.longitude then
    if not ('venue' = any(parts)) then
      parts := array_append(parts, 'location');
    end if;
  end if;
  if new.volunteer_openings is distinct from old.volunteer_openings then
    parts := array_append(parts, 'volunteer openings');
  end if;

  if array_length(parts, 1) is null then
    return new;
  end if;

  msg := 'Organiser updated the ' || array_to_string(parts, ', ') || '.';

  -- is_system = TRUE  → filtered out of the public broadcast feed.
  -- is_material = TRUE → considering RSVPs receive push, not just in-app.
  insert into public.event_updates (event_id, author_id, body, is_system, is_material)
  values (new.id, new.created_by, msg, true, true);

  return new;
end;
$$;

-- Recreate the trigger so it also fires when only volunteer_openings changes.
drop trigger if exists trg_notify_event_field_changes on public.events;

create trigger trg_notify_event_field_changes
  after update of date, end_time, location, latitude, longitude, volunteer_openings
  on public.events
  for each row
  execute function public.notify_event_field_changes();

comment on function public.notify_event_field_changes() is
  'Appends a material (is_system + is_material) event_updates row whenever a published events row changes date/end_time/location/coords/volunteer_openings, re-using the event-update notification webhook path.';
