// Copy to config.js for local development (config.js is gitignored — the
// deployed config.js is generated by scripts/build-frontend.js from env vars).
window.__CV_ENV = {
  SUPABASE_URL: "REPLACE_WITH_SUPABASE_URL",
  SUPABASE_ANON_KEY: "REPLACE_WITH_SUPABASE_PUBLISHABLE_ANON_KEY",
  // '' = same origin. For the two-server dev flow (static app on :3001,
  // Next API on :3000) set "http://localhost:3000".
  API_BASE_URL: "",
  MAPTILER_KEY: "",
};
