import type { EventCategory, PlaceCategory } from "@/types/db";

/** Human-readable labels for each event category. */
export const CATEGORY_LABELS: Record<EventCategory, string> = {
  "worship-prayer": "Worship & Prayer",
  "church-services": "Church Services",
  "outreach-missions": "Outreach & Missions",
  "markets-expos": "Markets & Expos",
  "sport-recreation": "Sport & Recreation",
  "arts-culture": "Arts & Culture",
  "social-gatherings": "Social Gatherings",
  "community-upliftment": "Community Upliftment",
  "education-equipping": "Education & Equipping",
  "marriage-family": "Marriage & Family",
  "mens-community": "Men's Community",
  "womens-community": "Women's Community",
  "youth-students": "Youth & Students",
  kids: "Kids",
  "care-recovery": "Care & Recovery",
  "members-only": "Members Only",
  "conferences-summits": "Conferences & Summits",
};

/** Shortened labels for constrained UI (e.g. cards). */
export const CATEGORY_LABELS_SHORT: Record<EventCategory, string> = {
  "worship-prayer": "Worship",
  "church-services": "Church",
  "outreach-missions": "Outreach",
  "markets-expos": "Markets",
  "sport-recreation": "Sport",
  "arts-culture": "Arts",
  "social-gatherings": "Social",
  "community-upliftment": "Upliftment",
  "education-equipping": "Education",
  "marriage-family": "Family",
  "mens-community": "Men's",
  "womens-community": "Women's",
  "youth-students": "Youth",
  kids: "Kids",
  "care-recovery": "Care",
  "members-only": "Members",
  "conferences-summits": "Conferences",
};

/** Hex colour per category — used for calendar, map markers, badges. */
export const CATEGORY_HEX: Record<EventCategory, string> = {
  "worship-prayer": "#B8860B",
  "church-services": "#D4AF37",
  "outreach-missions": "#1ABC9C",
  "markets-expos": "#F39C12",
  "sport-recreation": "#2ECC71",
  "arts-culture": "#FF6B35",
  "social-gatherings": "#E91E63",
  "community-upliftment": "#9B59B6",
  "education-equipping": "#3498DB",
  "marriage-family": "#E74C3C",
  "mens-community": "#34495E",
  "womens-community": "#C71585",
  "youth-students": "#FF8C42",
  kids: "#00BCD4",
  "care-recovery": "#8E44AD",
  "members-only": "#212121",
  "conferences-summits": "#5D6D7E",
};

/** Tailwind class strings for category badges. */
export const CATEGORY_BADGE_CLASSES: Record<EventCategory, string> = {
  "worship-prayer": "bg-[#B8860B]/15 text-[#7a5b08]",
  "church-services": "bg-[var(--gold-soft)] text-black",
  "outreach-missions": "bg-[#1ABC9C]/15 text-[#148f77]",
  "markets-expos": "bg-[#F39C12]/15 text-[#b7710c]",
  "sport-recreation": "bg-[#2ECC71]/15 text-[#1e8449]",
  "arts-culture": "bg-[#FF6B35]/15 text-[#c44e1e]",
  "social-gatherings": "bg-[#E91E63]/15 text-[#ad1457]",
  "community-upliftment": "bg-[#9B59B6]/15 text-[#7d3c98]",
  "education-equipping": "bg-[#3498DB]/15 text-[#21618c]",
  "marriage-family": "bg-[#E74C3C]/15 text-[#b03a2e]",
  "mens-community": "bg-[#34495E]/15 text-[#2c3e50]",
  "womens-community": "bg-[#C71585]/15 text-[#8e0c5c]",
  "youth-students": "bg-[#FF8C42]/15 text-[#c45a18]",
  kids: "bg-[#00BCD4]/15 text-[#00838f]",
  "care-recovery": "bg-[#8E44AD]/15 text-[#6c3483]",
  "members-only": "bg-[#212121]/10 text-[#212121]",
  "conferences-summits": "bg-[#5D6D7E]/15 text-[#3b4a5a]",
};

/**
 * Category colours for calendar events.
 * RSVP'd events override to gold at render time.
 */
export const CATEGORY_COLORS: Record<EventCategory, string> = {
  ...CATEGORY_HEX,
};

/** Selectable list for forms (create / edit). */
export const EVENT_CATEGORIES: { value: EventCategory; label: string }[] = [
  { value: "worship-prayer", label: "Worship & Prayer" },
  { value: "church-services", label: "Church Services" },
  { value: "outreach-missions", label: "Outreach & Missions" },
  { value: "markets-expos", label: "Markets & Expos" },
  { value: "sport-recreation", label: "Sport & Recreation" },
  { value: "arts-culture", label: "Arts & Culture" },
  { value: "social-gatherings", label: "Social Gatherings" },
  { value: "community-upliftment", label: "Community Upliftment" },
  { value: "education-equipping", label: "Education & Equipping" },
  { value: "marriage-family", label: "Marriage & Family" },
  { value: "mens-community", label: "Men's Community" },
  { value: "womens-community", label: "Women's Community" },
  { value: "youth-students", label: "Youth & Students" },
  { value: "kids", label: "Kids" },
  { value: "care-recovery", label: "Care & Recovery" },
  { value: "members-only", label: "Members Only" },
  { value: "conferences-summits", label: "Conferences & Summits" },
];

/** Filter list including "all" sentinel. */
export const CATEGORY_FILTERS: { value: EventCategory | "all"; label: string }[] = [
  { value: "all", label: "All categories" },
  ...EVENT_CATEGORIES,
];

/* ── Place categories ─────────────────────────────────── */

/** Human-readable labels for each place category. */
export const PLACE_CATEGORY_LABELS: Record<PlaceCategory, string> = {
  "churches-ministries": "Churches & Ministries",
  "hospitality-cafes": "Hospitality & Cafés",
  "recreation-sport": "Recreation & Sport",
  "media-broadcasting": "Media & Broadcasting",
  "retail-shopping": "Retail & Shopping",
  "health-wellness": "Health & Wellness",
  "education-training": "Education & Training",
  "arts-creative": "Arts & Creative",
  "christian-businesses": "Christian Businesses",
  "safe-spaces": "Safe Spaces",
};

/** Descriptions for place categories (shown as subtitle). */
export const PLACE_CATEGORY_DESCRIPTIONS: Record<PlaceCategory, string> = {
  "churches-ministries": "Churches, ministries, worship venues",
  "hospitality-cafes": "Coffee shops, restaurants, lounges",
  "recreation-sport": "Gyms, hikes, nature, sport venues",
  "media-broadcasting": "Radios, studios, concert halls",
  "retail-shopping": "Markets, malls, boutiques, stores",
  "health-wellness": "Clinics, wellness, pharmacies",
  "education-training": "Schools, libraries, training centres",
  "arts-creative": "Galleries, theatres, museums",
  "christian-businesses": "Kingdom-minded businesses & services",
  "safe-spaces": "Counselling, recovery, refuge venues",
};

/** Hex colour per place category. */
export const PLACE_CATEGORY_HEX: Record<PlaceCategory, string> = {
  "churches-ministries": "#D4AF37",
  "hospitality-cafes": "#8B4513",
  "recreation-sport": "#2ECC71",
  "media-broadcasting": "#9B59B6",
  "retail-shopping": "#E91E63",
  "health-wellness": "#E74C3C",
  "education-training": "#3498DB",
  "arts-creative": "#FF6B35",
  "christian-businesses": "#A67C00",
  "safe-spaces": "#B59CD9",
};

/** Selectable list for place categories. */
export const PLACE_CATEGORIES: { value: PlaceCategory; label: string }[] = [
  { value: "churches-ministries", label: "Churches & Ministries" },
  { value: "hospitality-cafes", label: "Hospitality & Cafés" },
  { value: "recreation-sport", label: "Recreation & Sport" },
  { value: "media-broadcasting", label: "Media & Broadcasting" },
  { value: "retail-shopping", label: "Retail & Shopping" },
  { value: "health-wellness", label: "Health & Wellness" },
  { value: "education-training", label: "Education & Training" },
  { value: "arts-creative", label: "Arts & Creative" },
  { value: "christian-businesses", label: "Christian Businesses" },
  { value: "safe-spaces", label: "Safe Spaces" },
];

/**
 * Map place category slugs to keywords matched against place name, description,
 * address, and DB category name for client-side filtering.
 */
export const PLACE_CATEGORY_KEYWORDS: Record<PlaceCategory, string[]> = {
  "churches-ministries": [
    "church", "ministry", "chapel", "cathedral", "parish", "worship", "worship venue",
    "sanctuary", "basilica", "mission station", "prayer house", "house of prayer",
    "hop", "boiler room", "upper room", "fellowship", "congregation",
    "revival center", "revival centre", "kingdom center", "kingdom centre",
    "bethel", "zion", "ecclesia", "ekklesia", "assembly", "assembly of god",
    "baptist", "methodist", "anglican", "presbyterian", "pentecostal",
    "charismatic", "catholic", "orthodox", "reformed", "apostolic",
    "prophetic house", "tabernacle", "temple", "tent", "marquee",
    "church plant", "home church", "simple church", "organic church", "oikos",
    "life group home", "cell church", "cell group venue", "church building",
    "community church", "bible church",
  ],
  "hospitality-cafes": [
    "coffee", "coffee shop", "cafe", "café", "bistro", "tea room", "tearoom",
    "tea house", "teahouse", "restaurant", "diner", "eatery", "food court",
    "bakery", "patisserie", "pub", "gastropub", "wine bar", "brewery",
    "cocktail bar", "lounge", "rooftop", "rooftop bar", "patio",
    "garden", "public garden", "botanical garden", "park", "picnic spot",
    "nature reserve", "pond", "lake", "river walk", "promenade", "boardwalk",
    "beach", "beachfront", "spa", "wellness spa", "massage",
    "retreat center", "retreat centre", "quiet place", "reading spot",
    "library cafe", "scenic viewpoint", "picnic area", "outdoor seating",
    "courtyard", "plaza", "square", "relax", "chill",
  ],
  "recreation-sport": [
    "gym", "fitness center", "fitness centre", "health club", "studio",
    "yoga studio", "pilates studio", "barre studio", "cycling studio",
    "spin studio", "crossfit box", "crossfit", "climbing gym", "boulder gym",
    "rock climbing", "sports club", "sports complex", "sport complex",
    "stadium", "arena", "field", "soccer field", "football field",
    "rugby field", "netball court", "tennis court", "squash court",
    "badminton court", "basketball court", "hockey field", "running track",
    "athletics track", "swimming pool", "pool", "aquatic centre", "aquatics",
    "martial arts", "dojo", "boxing gym", "mma gym", "dance studio",
    "hiking trail", "trail", "trailhead", "nature trail",
    "mountain bike trail", "mtb trail", "park run", "parkrun",
    "sports park", "fitness", "exercise",
  ],
  "media-broadcasting": [
    "radio", "radio station", "tv", "tv station", "television",
    "production house", "production studio", "recording studio",
    "music studio", "podcast studio", "podcast", "podcasts",
    "broadcast", "broadcaster", "broadcasting", "webcast", "live stream",
    "streaming", "stream", "live venue", "live music venue", "music venue",
    "concert hall", "concert venue", "theater", "theatre", "cinema",
    "movie theater", "multiplex", "imax", "drive in", "drive-in",
    "arena", "amphitheater", "amphitheatre", "auditorium", "newsroom",
    "publishing", "publisher", "media hub", "content studio",
    "game store", "gaming lounge", "esports venue", "esports",
    "game cafe", "arcade", "vr lounge", "technology", "tech hub",
    "innovation lab", "maker space", "coding studio", "electronics",
  ],
  "retail-shopping": [
    "shop", "shops", "store", "stores", "shopping", "shopping center",
    "shopping centre", "shopping mall", "mall", "market", "farmers market",
    "flea market", "craft market", "artisan market", "weekend market",
    "open-air market", "bazaar", "souk", "boutique", "boutiques",
    "concept store", "thrift store", "thrift shop", "second hand", "vintage",
    "christian bookshop", "christian bookstore", "faith based store",
    "faith-based store", "gifts", "gift shop", "homeware", "decor",
    "furniture store", "clothing store", "fashion", "apparel", "streetwear",
    "shoes", "jewelry", "jewellery", "pawn shop", "grocery", "grocer",
    "supermarket", "deli", "butchery", "organic store", "health store",
    "farm stall", "farmstall", "co-op", "retail",
  ],
  "health-wellness": [
    "clinic", "medical clinic", "doctor", "gp", "general practice",
    "surgery", "hospital", "medical centre", "medical center", "medicentre",
    "dentist", "dental", "orthodontist", "optometrist", "optometry",
    "eye clinic", "pharmacy", "chemist", "dispensary", "physiotherapy",
    "physio", "chiro", "chiropractor", "osteopath", "podiatrist",
    "psychologist", "counsellor", "counselor", "therapist",
    "counseling practice", "counselling practice", "psychiatrist",
    "psychiatric", "mental health clinic", "wellness centre",
    "wellness center", "holistic health", "naturopath", "homeopath",
    "biokineticist", "biokinetics", "nutritionist", "dietician",
    "rehabilitation", "rehab clinic", "medical spa", "maternity",
    "maternity hospital", "midwife", "lab", "pathology", "clinical lab",
    "blood bank", "first aid", "wellness", "medical", "health",
  ],
  "education-training": [
    "school", "primary school", "high school", "secondary school", "college",
    "university", "campus", "christian school", "private school",
    "public school", "bible college", "bible school", "seminary",
    "theological college", "theological seminary", "christian university",
    "library", "public library", "community library", "children's library",
    "learning center", "learning centre", "tutoring", "tutoring center",
    "remedial", "extra lessons", "training center", "training centre",
    "academy", "institute", "technical college", "tvet", "fet",
    "crèche", "creche", "preschool", "daycare", "playschool", "playgroup",
    "kindergarten", "adult education", "adult learning",
    "skills center", "skills centre", "research center", "research institute",
    "conference centre", "conference center", "lecture hall", "classroom",
    "study hall", "nursery school",
  ],
  "arts-creative": [
    "gallery", "art gallery", "studio", "art studio", "creative studio",
    "open studio", "artist studio", "art collective", "artists collective",
    "maker space", "makerspace", "workshop space", "craft shop",
    "craft workshop", "museum", "natural history museum", "art museum",
    "heritage site", "historical site", "cultural center", "cultural centre",
    "culture hub", "theatre", "theater", "black box", "playhouse",
    "opera house", "ballet", "performance venue", "performance hall",
    "arts venue", "arts hub", "music school", "music academy",
    "dance studio", "dance school", "drama school", "pottery studio",
    "ceramics studio", "sculpture garden", "sculpture park", "mural",
    "street art", "public art", "gallery space", "exhibition",
    "exhibition hall", "gallery walk", "artisan quarter", "cinema", "arts",
  ],
  "christian-businesses": [
    "christian business", "kingdom business", "marketplace ministry",
    "faith based business", "faith-based business", "christian owned",
    "christian-owned", "kingdom marketplace", "kingdom entrepreneur",
    "marketplace mountain", "seven mountains", "kingdom enterprise",
    "kingdom company", "kingdom firm", "kingdom services",
    "christian consultant", "christian consulting", "christian coaching",
    "christian financial", "christian accountant", "christian attorney",
    "christian lawyer", "christian dentist", "christian dental",
    "christian builder", "christian contractor", "christian architect",
    "christian designer", "christian printer", "christian marketing",
    "christian web design", "christian hosting", "christian agency",
    "christian publisher", "christian media", "christian record label",
    "christian wedding", "christian event planner", "christian travel",
    "christian tour", "kingdom investing", "kingdom finance",
    "ethical business", "redemptive business", "redemptive enterprise",
    "missional business", "social enterprise", "fair trade", "kingdom retailer",
    "kingdom store", "christian gym", "christian school",
  ],
  "safe-spaces": [
    "safe space", "safe house", "refuge", "shelter", "sanctuary",
    "house of refuge", "place of safety", "trauma centre", "trauma center",
    "crisis centre", "crisis center", "rape crisis", "domestic violence",
    "domestic abuse", "abuse shelter", "women's shelter", "womens shelter",
    "men's shelter", "youth shelter", "homeless shelter", "halfway house",
    "transition house", "rehabilitation house", "rehab", "recovery house",
    "sober living", "sober house", "freedom house", "set free centre",
    "set free center", "deliverance ministry", "counselling centre",
    "counseling centre", "counseling center", "counselling center",
    "pastoral care centre", "soul care centre", "soul care",
    "inner healing centre", "healing rooms", "prayer room",
    "intercession house", "quiet room", "listening room", "support group",
    "support meetings", "12 step", "twelve step", "celebrate recovery",
    "anonymous meeting", "grief support", "bereavement centre",
    "widow care", "orphan care", "foster care",
  ],
};

/**
 * Map event category slugs to keywords matched against event title,
 * description, location, and category name for client-side filtering.
 *
 * NOTE: A sibling keyword table lives in `src/lib/categorySuggest.ts` (KEYWORDS).
 * That one drives the *auto-suggest* heuristic on event creation; this one
 * drives *runtime search/filter matching*. When you add a new slug, update both,
 * AND the `CATEGORY_INTEREST_MAP` in `supabase/functions/_shared/category-interests.ts`.
 */
export const EVENT_CATEGORY_KEYWORDS: Record<EventCategory, string[]> = {
  "worship-prayer": [
    "worship", "worship night", "worship gathering", "worship encounter",
    "prayer", "prayer night", "prayer meeting", "prayer gathering",
    "prayer room", "prayer watch", "prayer walk", "prayer chain",
    "intercession", "intercessor", "intercessory prayer", "prophetic prayer",
    "warfare prayer", "prayer warfare", "prayer fast", "fasting", "fast",
    "tabernacle of prayer", "house of prayer", "boiler room", "upper room",
    "praise night", "praise and worship", "worship encounter night",
    "anointing", "outpouring", "presence", "soaking", "soaking worship",
    "contemplative", "silent prayer", "solemn assembly", "vigil",
    "all night prayer", "all-night prayer", "early morning prayer",
    "dawn prayer", "watch", "watchman", "watchmen", "harp and bowl",
    "twenty four seven", "24/7 prayer", "ihop", "prayer summit",
    "corporate worship", "corporate prayer", "psalms", "selah",
    "prayer encounter", "global day of prayer", "worship centre",
  ],
  "church-services": [
    "service", "sunday service", "saturday service", "friday service",
    "sunday", "saturday", "church", "church service", "worship service",
    "main service", "morning service", "evening service", "night service",
    "gathering", "celebration service", "communion",
    "holy communion", "lord's supper", "baptism", "baptismal service",
    "dedication", "child dedication", "baby dedication", "congregation",
    "assembly", "house of prayer", "house church", "simple church",
    "church plant", "house gathering", "open church", "revival",
    "revival service", "thanksgiving", "thanksgiving service", "sermon",
    "preaching", "altar call", "ministry time", "prophetic service",
    "healing service", "anointing service", "charismatic", "liturgy",
    "liturgical", "easter service", "christmas service", "candle service",
  ],
  "outreach-missions": [
    "mission", "missions", "mission trip", "short term mission",
    "short-term missions", "missionary", "missionary visit", "sending",
    "commissioning", "outreach trip", "evangelism", "evangelise",
    "evangelistic", "gospel", "gospel outreach", "soul winning", "souls",
    "great commission", "nations", "unreached", "unengaged",
    "10/40 window", "frontier missions", "church planting",
    "disciple making movement", "dmm", "harvest", "kingdom advance",
    "go", "gospel share", "tract", "tracting", "street evangelism",
    "open air", "crusade", "gospel crusade", "tent meeting",
    "healing crusade", "market outreach", "mall outreach",
    "school outreach", "prison ministry", "hospital outreach",
    "orphanage visit", "missions conference", "missions sunday",
    "missions weekend", "missions night", "send", "sent ones", "missional",
  ],
  "markets-expos": [
    "market", "markets", "market day", "farmers market", "farmer's market",
    "flea market", "craft market", "artisan market", "weekend market",
    "night market", "open-air market", "kingdom market", "kingdom expo",
    "kingdom marketplace", "kingdom business expo", "marketplace ministry",
    "expo", "exposition", "trade show", "trade fair", "showcase",
    "vendor showcase", "vendor day", "vendor village", "stall day",
    "pop up", "pop-up", "pop up market", "pop-up market", "bazaar",
    "souk", "fair", "fete", "fête", "kermis", "carnival",
    "christmas market", "easter market", "spring market",
    "harvest market", "harvest festival", "small business fair",
    "christian business expo", "ministry expo", "outreach expo",
    "creative expo", "wellness expo", "wedding expo", "youth expo",
    "tech expo", "ministries expo", "stalls", "vendors", "exhibition",
    "exhibitor", "stand", "kiosk", "trade",
  ],
  "sport-recreation": [
    "sport", "sports", "soccer", "football", "basketball", "netball",
    "volleyball", "cricket", "rugby", "tennis", "squash", "badminton",
    "table tennis", "hockey", "golf", "running", "runners", "run", "jog",
    "park run", "parkrun", "fun run", "race", "trail", "trail run",
    "hiking", "hike", "walk", "prayer walk", "nature walk",
    "bike", "cycling", "mountain biking", "swimming", "swim", "pool",
    "gym", "cross fit", "crossfit", "athletics", "fitness", "workout",
    "kids sport", "sport day", "tournament", "league", "team sport",
    "adventure", "outdoors", "active", "game day", "boot camp", "recreation",
  ],
  "arts-culture": [
    "concert", "music", "band", "worship band", "live music", "acoustic",
    "jam", "jam night", "jamming", "open mic", "open-mic", "talent show",
    "gala", "variety show", "choir", "choir night", "gospel choir",
    "performance", "show", "stage", "theatre", "drama", "skit", "play",
    "musical", "production", "comedy", "comedy night", "clean comedy",
    "storytelling", "spoken word", "poetry", "slam", "dance",
    "dance night", "street dance", "creative night", "showcase", "artists",
    "festival", "film night", "movie night", "cinema", "screening",
    "worship concert", "block party", "kingdom culture", "cultural night",
    "expression", "entertainment", "gig", "art exhibition",
    "art opening", "gallery night", "exhibition", "creatives", "culture",
    "arts night", "creative arts",
  ],
  "social-gatherings": [
    "braai", "barbecue", "bbq", "potluck", "picnic", "picnic in the park",
    "coffee", "coffee morning", "coffee date", "brunch", "breakfast",
    "lunch", "dinner", "supper", "dinner party", "house party",
    "housewarming", "game night", "games night", "board games", "trivia",
    "quiz night", "bonfire", "fireside", "fire pit", "hangout", "hang out",
    "meet and greet", "meetup", "mingle", "social", "social evening",
    "fellowship", "connection", "connect night", "friendship",
    "community meal", "community dinner", "hosted dinner", "shared meal",
    "karaoke", "movie night", "celebration", "get together", "gathering",
    "birthday", "anniversary", "welcome", "farewell", "soirée", "soiree",
  ],
  "community-upliftment": [
    "outreach", "community outreach", "soup kitchen", "feeding scheme",
    "food drive", "blanket drive", "clothing drive", "clean up", "cleanup",
    "beach cleanup", "neighbourhood clean", "painting day", "building day",
    "service project", "service day", "community service", "volunteering",
    "volunteer", "volunteer day", "mission trip", "local mission",
    "uplift", "upliftment", "transformation", "adoption", "fostering",
    "mentoring", "tutoring", "literacy", "homeless", "shelter", "soup run",
    "street outreach", "park outreach", "township outreach", "orphan care",
    "widow care", "elderly care", "justice", "social justice",
    "anti-human-trafficking", "human trafficking awareness", "restoration",
    "restore", "hope", "dignity", "serve", "servant", "salt and light",
    "love in action", "fundraiser", "charity",
  ],
  "education-equipping": [
    "class", "course", "workshop", "seminar", "training", "short course",
    "masterclass", "webinar", "lecture", "teaching", "study", "study group",
    "home group", "bible study", "book study", "book club", "cell group",
    "small group", "life group", "lifegroup", "theology", "hermeneutics",
    "apologetics", "discipleship class", "catechism", "new believers",
    "new believers class", "financial literacy", "kingdom business",
    "marketplace", "leadership", "leadership training", "school of ministry",
    "school of healing", "prophetic school", "foundations", "fundamentals",
    "college", "institute", "academy", "scholarship", "mentorship", "tutor",
    "study night", "homework help", "learn", "learners", "learning",
    "growth", "education", "alpha", "alpha course",
    "equip", "equipping", "training day", "intensive", "practical training",
    "practicum", "impartation", "activation", "prophetic activation",
    "healing training", "deliverance training", "evangelism training",
    "discipleship training", "ministry school",
    "school of supernatural ministry", "bsm", "sozo training", "bethel",
    "iris", "ywam", "dts", "discipleship training school",
    "servant leadership", "mentoring", "coaching", "shadowing", "internship",
    "volunteer training", "usher training", "worship training",
    "worship team training", "musicians training", "tech team training",
    "sound training", "church planting school", "seminary", "bible college",
    "theological training", "elder training", "deacon training",
    "certification", "skill up",
  ],
  "marriage-family": [
    "marriage", "marriages", "marriage course", "pre marriage",
    "pre-marriage", "premarriage", "premarital", "married couples",
    "couples", "couples night", "couples retreat", "date night", "dates",
    "date", "alpha marriage", "marriage prep", "engaged", "engagement",
    "engagement course", "newlyweds", "newly weds", "honeymoon prep",
    "anniversary", "wedding", "weddings", "vow renewal",
    "marriage counseling", "marriage coaching", "marriage mentoring",
    "family", "family life", "family night", "family day", "families",
    "parenting", "parenting workshop", "parents", "husband", "wife",
    "spouse", "husbands", "wives", "love languages", "intimacy",
    "conflict resolution", "communication workshop", "finances in marriage",
    "parenting together", "covenant", "purity", "headship", "submission",
    "household", "marriage ministry", "couple ministry", "alpha couples",
    "couple", "romance", "blended family", "single parent", "step family",
    "stepfamily", "family ministry", "household of faith",
  ],
  "mens-community": [
    "men", "mens", "men's", "mens night", "mens group", "mens breakfast",
    "mens lunch", "mens conference", "mens gathering", "brothers",
    "brotherhood", "iron sharpens iron", "iron sharpens", "father",
    "fatherhood", "fathers", "dads", "dad", "father son", "men of valour",
    "men of valor", "bootcamp", "boot camp", "stag", "bachelor",
    "bachelor party", "ministry to men", "guys night", "boys night",
    "lads", "wild at heart", "band of brothers", "man up", "accountability",
    "accountability group", "discipleship men", "mentoring men",
    "camp for men", "fishing trip", "hunting trip", "golf day", "mens sport",
    "braai night", "cigars and whiskey", "whiskey night", "kingdom men",
    "masculine", "manliness", "men's ministry", "fatherheart",
  ],
  "womens-community": [
    "women", "women's", "womens", "ladies", "ladies night", "ladies lunch",
    "ladies breakfast", "ladies tea", "ladies brunch", "womens conference",
    "ladies conference", "sisterhood", "sisters", "mothers", "motherhood",
    "mums", "moms", "mom", "mum", "mother daughter", "daughters",
    "princess", "pampering", "pamper day", "pamper evening", "high tea",
    "afternoon tea", "tea party", "spa day", "makeup workshop",
    "craft day", "scrapbooking", "craft evening", "book club ladies",
    "ladies book club", "womens bible study", "prayer women",
    "intercessors women", "virtuous woman", "proverbs 31", "esther",
    "ruth", "kingdom woman", "feminine", "womanhood", "single mums",
    "single moms", "baby shower", "bridal shower", "widows",
    "women's ministry", "daughters of the king",
  ],
  "youth-students": [
    "youth", "youth group", "youth night", "youth gathering", "youth meeting",
    "youth camp", "youth retreat", "youth conference", "youth weekend",
    "youth worship", "youth band", "youth event", "youth ministry",
    "high school", "highschool", "scholar", "scholars", "teen", "teens",
    "teenager", "teenagers", "tween", "tweens", "preteen", "preteens",
    "young people", "young adults", "ya", "ya night", "twenties", "20s",
    "30s", "thirties", "campus", "campus ministry", "campus event",
    "varsity", "university", "uni", "uni group", "students", "student night",
    "student group", "student ministry", "student outreach", "tertiary",
    "college students", "tertiary students", "next gen", "next generation",
    "rising generation", "youth pastors", "youth leaders", "youth culture",
    "youth fest", "youth fest", "youth festival", "matric", "post-matric",
    "gap year", "young leaders", "leadership youth",
  ],
  kids: [
    "kids", "kids club", "kids church", "children", "children's church",
    "childrens", "childcare", "childminder", "crèche", "creche",
    "nursery", "sunday school", "sabbath school", "bible school", "vbs",
    "vacation bible school", "holiday club", "kids camp", "kidz",
    "kidzone", "kiddies", "toddler", "toddler group", "toddlers",
    "pre-school", "preschool", "play group", "playgroup", "storytime",
    "craft", "kids craft", "kids party", "inflatables", "jumping castle",
    "face painting", "treasure hunt", "puppet show", "puppet ministry",
    "kids worship", "kids praise", "kids dance", "kids drama",
    "kids discipleship", "kids bible", "young disciples", "primary school",
    "infants", "juniors", "mini-church", "children's ministry", "family day",
    "child", "kindergarten",
  ],
  "care-recovery": [
    "recovery", "addiction", "substance abuse", "rehab", "sobriety",
    "sober", "clean and sober", "aa", "alcoholics anonymous", "na",
    "narcotics anonymous", "celebrate recovery", "support group",
    "deliverance", "freedom", "freedom house", "set free", "chains broken",
    "rehabilitation", "detox", "healing journey", "12 step", "twelve step",
    "step study", "inner healing", "trauma healing", "trauma therapy",
    "abuse survivors", "survivor", "porn addiction", "pornography", "lust",
    "sex addiction", "grief", "bereavement", "divorce care",
    "divorce recovery", "single parents", "healing", "healing ministry",
    "restoration", "restore", "ministry of reconciliation",
    "counseling group", "peer support", "sponsor", "fellowship recovery",
    "life change", "testimony", "new life", "born again recovery",
    "beauty for ashes",
    "care", "counseling", "counselling", "christian counseling",
    "soul care", "soulcare", "pastoral care",
    "healing room", "healing rooms", "prayer ministry", "prayer clinic",
    "sozo", "theophostic", "freedom ministry",
    "grief share", "bereavement support", "divorce support", "divorced",
    "widow support", "widow's care", "orphan care", "foster care support",
    "elderly care", "visitation", "hospital visit", "pastoral visit",
    "home visit", "care group", "care team", "helps ministry",
    "mercy ministry", "compassion", "kindness", "love walk",
    "emotional support", "mental health", "depression", "anxiety", "burnout",
    "chaplaincy", "chaplain",
  ],
  "members-only": [
    "members", "members only", "members meeting", "congregational meeting",
    "agm", "annual general meeting", "quarterly meeting", "ministry team",
    "leaders meeting", "elders meeting", "deacons meeting",
    "staff meeting", "team meeting", "volunteer meeting",
    "volunteer appreciation", "ministry family", "partners",
    "partners only", "partners event", "partner meeting", "private event",
    "closed", "closed event", "invite only", "invitation only", "internal",
    "internal event", "church family", "church family only", "core team",
    "core", "inner circle", "intercessors meeting", "prayer team",
    "ministry team meeting", "ushers meeting", "worship team meeting",
    "sound team meeting", "production team", "hosts meeting",
    "welcome team", "committee", "committee meeting", "board meeting",
    "council", "elders", "deacons", "trustees", "governance", "members-only",
    "leadership team",
  ],
  "conferences-summits": [
    "conference", "conferences", "convention", "congress", "summit",
    "summits", "kingdom conference", "kingdom summit", "leaders conference",
    "leaders summit", "leadership conference", "leadership summit",
    "ministry conference", "missions conference", "worship conference",
    "prophetic conference", "healing conference", "youth conference",
    "womens conference", "mens conference", "couples conference",
    "marriage conference", "family conference", "kingdom business conference",
    "marketplace conference", "marketplace summit", "global gathering",
    "regional conference", "national conference", "national gathering",
    "annual conference", "annual gathering", "biennial conference",
    "encounter", "encounter weekend", "vision conference", "vision summit",
    "strategy summit", "think tank", "symposium", "colloquium", "forum",
    "kingdom forum", "ministry forum", "leadership forum", "leaders forum",
    "ministerial summit", "pastors conference", "pastors summit",
    "denomination conference", "denominational conference",
    "international conference", "global summit", "kingdom convention",
    "convocation", "ministerial convocation", "plenary",
    "main session", "breakout session",
  ],
};
