import type { EventCategory, PlaceCategory } from "@/types/db";

/** Human-readable labels for each event category. */
export const CATEGORY_LABELS: Record<EventCategory, string> = {
  entertainment: "Entertainment",
  "sport-fun": "Sport Fun",
  "social-fun": "Social Fun",
  "community-upliftment": "Community Upliftment",
  education: "Education",
  church: "Church",
  missional: "Missional",
  "marriage-and-couples": "Marriage & Couples",
  mens: "Mens",
  womens: "Womens",
  kids: "Kids",
  recovery: "Recovery",
  equip: "Equip",
  weekend: "Weekend",
  "members-only": "Members Only",
  care: "Care",
};

/** Shortened labels for constrained UI (e.g. cards). */
export const CATEGORY_LABELS_SHORT: Record<EventCategory, string> = {
  entertainment: "Entertainment",
  "sport-fun": "Sport",
  "social-fun": "Social",
  "community-upliftment": "Upliftment",
  education: "Education",
  church: "Church",
  missional: "Missional",
  "marriage-and-couples": "Couples",
  mens: "Mens",
  womens: "Womens",
  kids: "Kids",
  recovery: "Recovery",
  equip: "Equip",
  weekend: "Weekend",
  "members-only": "Members",
  care: "Care",
};

/** Hex colour per category — used for calendar, map markers, badges. */
export const CATEGORY_HEX: Record<EventCategory, string> = {
  entertainment: "#FF6B35",
  "sport-fun": "#2ECC71",
  "social-fun": "#E91E63",
  "community-upliftment": "#9B59B6",
  education: "#3498DB",
  church: "#D4AF37",
  missional: "#1ABC9C",
  "marriage-and-couples": "#E74C3C",
  mens: "#34495E",
  womens: "#F39C12",
  kids: "#00BCD4",
  recovery: "#8E44AD",
  equip: "#27AE60",
  weekend: "#FF9800",
  "members-only": "#212121",
  // Soft lilac — restorative, calming, distinct from Recovery's vivid purple.
  care: "#B59CD9",
};

/** Tailwind class strings for category badges. */
export const CATEGORY_BADGE_CLASSES: Record<EventCategory, string> = {
  entertainment: "bg-[#FF6B35]/15 text-[#c44e1e]",
  "sport-fun": "bg-[#2ECC71]/15 text-[#1e8449]",
  "social-fun": "bg-[#E91E63]/15 text-[#ad1457]",
  "community-upliftment": "bg-[#9B59B6]/15 text-[#7d3c98]",
  education: "bg-[#3498DB]/15 text-[#21618c]",
  church: "bg-[var(--gold-soft)] text-black",
  missional: "bg-[#1ABC9C]/15 text-[#148f77]",
  "marriage-and-couples": "bg-[#E74C3C]/15 text-[#b03a2e]",
  mens: "bg-[#34495E]/15 text-[#2c3e50]",
  womens: "bg-[#F39C12]/15 text-[#b7710c]",
  kids: "bg-[#00BCD4]/15 text-[#00838f]",
  recovery: "bg-[#8E44AD]/15 text-[#6c3483]",
  equip: "bg-[#27AE60]/15 text-[#1e8449]",
  weekend: "bg-[#FF9800]/15 text-[#e65100]",
  "members-only": "bg-[#212121]/10 text-[#212121]",
  care: "bg-[#B59CD9]/20 text-[#5d3f8a]",
};

/**
 * Category colours for calendar events.
 * RSVP'd events override to gold at render time.
 */
export const CATEGORY_COLORS: Record<EventCategory, string> = {
  ...CATEGORY_HEX,
};

/** Selectable list for forms (create / edit). */
export const EVENT_CATEGORIES: { value: EventCategory; label: string }[] = [
  { value: "entertainment", label: "Entertainment" },
  { value: "sport-fun", label: "Sport Fun" },
  { value: "social-fun", label: "Social Fun" },
  { value: "community-upliftment", label: "Community Upliftment" },
  { value: "education", label: "Education" },
  { value: "church", label: "Church" },
  { value: "missional", label: "Missional" },
  { value: "marriage-and-couples", label: "Marriage & Couples" },
  { value: "mens", label: "Mens" },
  { value: "womens", label: "Womens" },
  { value: "kids", label: "Kids" },
  { value: "care", label: "Care" },
  { value: "recovery", label: "Recovery" },
  { value: "equip", label: "Equip" },
  { value: "weekend", label: "Weekend" },
  { value: "members-only", label: "Members Only" },
];

/** Filter list including "all" sentinel. */
export const CATEGORY_FILTERS: { value: EventCategory | "all"; label: string }[] = [
  { value: "all", label: "All categories" },
  ...EVENT_CATEGORIES,
];

/* ── Place categories ─────────────────────────────────── */

/** Human-readable labels for each place category.
 *  NOTE: the `shopping` slug is retained as a DB enum value — we only changed
 *  the user-facing label to "Stores" per product direction, avoiding a
 *  destructive enum migration. */
export const PLACE_CATEGORY_LABELS: Record<PlaceCategory, string> = {
  church: "Church",
  relax: "Relax",
  exercise: "Exercise",
  media: "Media",
  shopping: "Stores",
  health: "Health",
  education: "Education",
  arts: "Arts & Culture",
};

/** Descriptions for place categories (shown as subtitle). */
export const PLACE_CATEGORY_DESCRIPTIONS: Record<PlaceCategory, string> = {
  church: "Churches, ministries, worship venues",
  relax: "Coffee shops, restaurants, parks",
  exercise: "Gyms, hikes, nature, sport venues",
  media: "Radio, concert halls, stadiums, gaming",
  shopping: "Markets, malls, boutiques, stores",
  health: "Clinics, wellness, pharmacies",
  education: "Schools, libraries, training centres",
  arts: "Galleries, theatres, museums",
};

/** Hex colour per place category. */
export const PLACE_CATEGORY_HEX: Record<PlaceCategory, string> = {
  church: "#D4AF37",
  relax: "#8B4513",
  exercise: "#2ECC71",
  media: "#9B59B6",
  shopping: "#E91E63",
  health: "#E74C3C",
  education: "#3498DB",
  arts: "#FF6B35",
};

/** Selectable list for place categories. */
export const PLACE_CATEGORIES: { value: PlaceCategory; label: string }[] = [
  { value: "church", label: "Church" },
  { value: "relax", label: "Relax" },
  { value: "exercise", label: "Exercise" },
  { value: "media", label: "Media" },
  { value: "shopping", label: "Stores" },
  { value: "health", label: "Health" },
  { value: "education", label: "Education" },
  { value: "arts", label: "Arts & Culture" },
];

/**
 * Map place category slugs to keywords matched against place name, description,
 * address, and DB category name for client-side filtering.
 *
 * Each array contains ≥50 keywords spanning common search terms, Christian
 * community vocabulary (home cells, prayer houses, boiler rooms), and niche
 * locale-specific synonyms (e.g. "medicentre", "parkrun", "farmstall").
 */
export const PLACE_CATEGORY_KEYWORDS: Record<PlaceCategory, string[]> = {
  church: [
    "church", "ministry", "chapel", "cathedral", "parish", "worship", "worship venue",
    "sanctuary", "basilica", "mission station", "prayer house", "house of prayer",
    "hop", "boiler room", "upper room", "fellowship", "congregation",
    "revival center", "revival centre", "kingdom center", "kingdom centre",
    "bethel", "zion", "ecclesia", "ekklesia", "assembly", "assembly of god",
    "baptist", "methodist", "anglican", "presbyterian", "pentecostal",
    "charismatic", "catholic", "orthodox", "reformed", "apostolic",
    "prophetic house", "tabernacle", "temple", "tent", "marquee",
    "church plant", "home church", "simple church", "organic church", "oikos",
    "life group home", "cell church", "cell group venue", "church building",
    "community church", "bible church",
  ],
  relax: [
    "coffee", "coffee shop", "cafe", "café", "bistro", "tea room", "tearoom",
    "tea house", "teahouse", "restaurant", "diner", "eatery", "food court",
    "bakery", "patisserie", "pub", "gastropub", "wine bar", "brewery",
    "cocktail bar", "lounge", "rooftop", "rooftop bar", "patio",
    "garden", "public garden", "botanical garden", "park", "picnic spot",
    "nature reserve", "pond", "lake", "river walk", "promenade", "boardwalk",
    "beach", "beachfront", "spa", "wellness spa", "massage",
    "retreat center", "retreat centre", "quiet place", "reading spot",
    "library cafe", "scenic viewpoint", "picnic area", "outdoor seating",
    "courtyard", "plaza", "square", "relax", "chill",
  ],
  exercise: [
    "gym", "fitness center", "fitness centre", "health club", "studio",
    "yoga studio", "pilates studio", "barre studio", "cycling studio",
    "spin studio", "crossfit box", "crossfit", "climbing gym", "boulder gym",
    "rock climbing", "sports club", "sports complex", "sport complex",
    "stadium", "arena", "field", "soccer field", "football field",
    "rugby field", "netball court", "tennis court", "squash court",
    "badminton court", "basketball court", "hockey field", "running track",
    "athletics track", "swimming pool", "pool", "aquatic centre", "aquatics",
    "martial arts", "dojo", "boxing gym", "mma gym", "dance studio",
    "hiking trail", "trail", "trailhead", "nature trail",
    "mountain bike trail", "mtb trail", "park run", "parkrun",
    "sports park", "fitness", "exercise",
  ],
  media: [
    "radio", "radio station", "tv", "tv station", "television",
    "production house", "production studio", "recording studio",
    "music studio", "podcast studio", "podcast", "podcasts",
    "broadcast", "broadcaster", "broadcasting", "webcast", "live stream",
    "streaming", "stream", "live venue", "live music venue", "music venue",
    "concert hall", "concert venue", "theater", "theatre", "cinema",
    "movie theater", "multiplex", "imax", "drive in", "drive-in",
    "arena", "amphitheater", "amphitheatre", "auditorium", "newsroom",
    "publishing", "publisher", "media hub", "content studio",
    "game store", "gaming lounge", "esports venue", "esports",
    "game cafe", "arcade", "vr lounge", "technology", "tech hub",
    "innovation lab", "maker space", "coding studio", "electronics",
  ],
  shopping: [
    "shop", "shops", "store", "stores", "shopping", "shopping center",
    "shopping centre", "shopping mall", "mall", "market", "farmers market",
    "flea market", "craft market", "artisan market", "weekend market",
    "open-air market", "bazaar", "souk", "boutique", "boutiques",
    "concept store", "thrift store", "thrift shop", "second hand", "vintage",
    "christian bookshop", "christian bookstore", "faith based store",
    "faith-based store", "gifts", "gift shop", "homeware", "decor",
    "furniture store", "clothing store", "fashion", "apparel", "streetwear",
    "shoes", "jewelry", "jewellery", "pawn shop", "grocery", "grocer",
    "supermarket", "deli", "butchery", "organic store", "health store",
    "farm stall", "farmstall", "co-op", "retail",
  ],
  health: [
    "clinic", "medical clinic", "doctor", "gp", "general practice",
    "surgery", "hospital", "medical centre", "medical center", "medicentre",
    "dentist", "dental", "orthodontist", "optometrist", "optometry",
    "eye clinic", "pharmacy", "chemist", "dispensary", "physiotherapy",
    "physio", "chiro", "chiropractor", "osteopath", "podiatrist",
    "psychologist", "counsellor", "counselor", "therapist",
    "counseling practice", "counselling practice", "psychiatrist",
    "psychiatric", "mental health clinic", "wellness centre",
    "wellness center", "holistic health", "naturopath", "homeopath",
    "biokineticist", "biokinetics", "nutritionist", "dietician",
    "rehabilitation", "rehab clinic", "medical spa", "maternity",
    "maternity hospital", "midwife", "lab", "pathology", "clinical lab",
    "blood bank", "first aid", "wellness", "medical", "health",
  ],
  education: [
    "school", "primary school", "high school", "secondary school", "college",
    "university", "campus", "christian school", "private school",
    "public school", "bible college", "bible school", "seminary",
    "theological college", "theological seminary", "christian university",
    "library", "public library", "community library", "children's library",
    "learning center", "learning centre", "tutoring", "tutoring center",
    "remedial", "extra lessons", "training center", "training centre",
    "academy", "institute", "technical college", "tvet", "fet",
    "crèche", "creche", "preschool", "daycare", "playschool", "playgroup",
    "kindergarten", "adult education", "adult learning",
    "skills center", "skills centre", "research center", "research institute",
    "conference centre", "conference center", "lecture hall", "classroom",
    "study hall", "nursery school",
  ],
  arts: [
    "gallery", "art gallery", "studio", "art studio", "creative studio",
    "open studio", "artist studio", "art collective", "artists collective",
    "maker space", "makerspace", "workshop space", "craft shop",
    "craft workshop", "museum", "natural history museum", "art museum",
    "heritage site", "historical site", "cultural center", "cultural centre",
    "culture hub", "theatre", "theater", "black box", "playhouse",
    "opera house", "ballet", "performance venue", "performance hall",
    "arts venue", "arts hub", "music school", "music academy",
    "dance studio", "dance school", "drama school", "pottery studio",
    "ceramics studio", "sculpture garden", "sculpture park", "mural",
    "street art", "public art", "gallery space", "exhibition",
    "exhibition hall", "gallery walk", "artisan quarter", "cinema", "arts",
  ],
};

/**
 * Map event category slugs to keywords matched against event title,
 * description, location, and category name for client-side filtering.
 *
 * Each array contains ≥50 keywords blending common search terms with
 * Christian community vocabulary (home cells, cell groups, life groups,
 * prayer triplets, intercession, prophetic, sozo, impartation, etc.).
 * Kept lowercase; matching uses `text.includes(kw)` so singular forms
 * already cover most plurals.
 */
export const EVENT_CATEGORY_KEYWORDS: Record<EventCategory, string[]> = {
  entertainment: [
    "concert", "music", "band", "worship band", "live music", "acoustic",
    "jam", "jam night", "jamming", "open mic", "open-mic", "talent show",
    "gala", "variety show", "choir", "choir night", "gospel choir",
    "performance", "show", "stage", "theatre", "drama", "skit", "play",
    "musical", "production", "comedy", "comedy night", "clean comedy",
    "storytelling", "spoken word", "poetry", "slam", "dance",
    "dance night", "street dance", "creative night", "showcase", "artists",
    "festival", "film night", "movie night", "cinema", "screening",
    "worship concert", "block party", "kingdom culture", "cultural night",
    "expression", "entertainment", "gig",
  ],
  "sport-fun": [
    "sport", "sports", "soccer", "football", "basketball", "netball",
    "volleyball", "cricket", "rugby", "tennis", "squash", "badminton",
    "table tennis", "hockey", "golf", "running", "runners", "run", "jog",
    "park run", "parkrun", "fun run", "race", "trail", "trail run",
    "hiking", "hike", "walk", "prayer walk", "nature walk",
    "bike", "cycling", "mountain biking", "swimming", "swim", "pool",
    "gym", "cross fit", "crossfit", "athletics", "fitness", "workout",
    "kids sport", "sport day", "tournament", "league", "team sport",
    "adventure", "outdoors", "active", "game day", "boot camp",
  ],
  "social-fun": [
    "braai", "barbecue", "bbq", "potluck", "picnic", "picnic in the park",
    "coffee", "coffee morning", "coffee date", "brunch", "breakfast",
    "lunch", "dinner", "supper", "dinner party", "house party",
    "housewarming", "game night", "games night", "board games", "trivia",
    "quiz night", "bonfire", "fireside", "fire pit", "hangout", "hang out",
    "meet and greet", "meetup", "mingle", "social", "social evening",
    "fellowship", "connection", "connect night", "friendship",
    "community meal", "community dinner", "hosted dinner", "shared meal",
    "karaoke", "movie night", "celebration", "get together", "gathering",
    "birthday", "anniversary", "welcome", "farewell", "soirée", "soiree",
  ],
  "community-upliftment": [
    "outreach", "community outreach", "soup kitchen", "feeding scheme",
    "food drive", "blanket drive", "clothing drive", "clean up", "cleanup",
    "beach cleanup", "neighbourhood clean", "painting day", "building day",
    "service project", "service day", "community service", "volunteering",
    "volunteer", "volunteer day", "mission trip", "local mission",
    "uplift", "upliftment", "transformation", "adoption", "fostering",
    "mentoring", "tutoring", "literacy", "homeless", "shelter", "soup run",
    "street outreach", "park outreach", "township outreach", "orphan care",
    "widow care", "elderly care", "justice", "social justice",
    "anti-human-trafficking", "human trafficking awareness", "restoration",
    "restore", "hope", "dignity", "serve", "servant", "salt and light",
    "love in action", "fundraiser", "charity",
  ],
  education: [
    "class", "course", "workshop", "seminar", "conference", "training",
    "short course", "masterclass", "webinar", "lecture", "teaching",
    "study", "study group", "home group", "bible study", "book study",
    "book club", "cell group", "small group", "life group", "lifegroup",
    "theology", "hermeneutics", "apologetics", "discipleship class",
    "catechism", "new believers", "new believers class",
    "financial literacy", "kingdom business", "marketplace",
    "leadership", "leadership training", "school of ministry",
    "school of healing", "prophetic school", "foundations", "fundamentals",
    "college", "institute", "academy", "scholarship", "mentorship",
    "tutor", "study night", "homework help", "learn", "learners",
    "learning", "growth", "education", "alpha", "alpha course",
  ],
  church: [
    "service", "sunday service", "saturday service", "friday service",
    "sunday", "saturday", "church", "church service", "worship service",
    "main service", "morning service", "evening service", "night service",
    "gathering", "celebration service", "prayer service", "communion",
    "holy communion", "lord's supper", "baptism", "baptismal service",
    "dedication", "child dedication", "baby dedication", "congregation",
    "assembly", "house of prayer", "house church", "simple church",
    "church plant", "house gathering", "open church", "revival",
    "revival service", "thanksgiving", "thanksgiving service", "sermon",
    "preaching", "altar call", "ministry time", "prophetic service",
    "healing service", "anointing service", "charismatic", "liturgy",
    "liturgical", "easter service", "christmas service", "candle service",
    "prayer meeting", "vigil", "corporate worship",
  ],
  missional: [
    "mission", "missions", "mission trip", "short term mission",
    "short-term missions", "missionary", "missionary visit", "sending",
    "commissioning", "outreach trip", "evangelism", "evangelise",
    "evangelistic", "gospel", "gospel outreach", "soul winning", "souls",
    "great commission", "nations", "unreached", "unengaged",
    "10/40 window", "frontier missions", "church planting",
    "disciple making movement", "dmm", "harvest", "kingdom advance",
    "go", "gospel share", "tract", "tracting", "street evangelism",
    "open air", "crusade", "gospel crusade", "tent meeting",
    "healing crusade", "market outreach", "mall outreach",
    "school outreach", "prison ministry", "hospital outreach",
    "orphanage visit", "missions conference", "missions sunday",
    "missions weekend", "missions night", "send", "sent ones", "missional",
  ],
  "marriage-and-couples": [
    "marriage", "marriages", "marriage course", "pre marriage",
    "pre-marriage", "premarriage", "premarital", "married couples",
    "couples", "couples night", "couples retreat", "date night", "dates",
    "date", "alpha marriage", "marriage prep", "engaged", "engagement",
    "engagement course", "newlyweds", "newly weds", "honeymoon prep",
    "anniversary", "wedding", "weddings", "vow renewal",
    "marriage counseling", "marriage coaching", "marriage mentoring",
    "family", "family life", "husband", "wife", "spouse", "husbands",
    "wives", "love languages", "intimacy", "conflict resolution",
    "communication workshop", "finances in marriage",
    "parenting together", "covenant", "purity", "headship", "submission",
    "household", "marriage ministry", "couple ministry", "alpha couples",
    "couple", "romance",
  ],
  mens: [
    "men", "mens", "men's", "mens night", "mens group", "mens breakfast",
    "mens lunch", "mens conference", "mens gathering", "brothers",
    "brotherhood", "iron sharpens iron", "iron sharpens", "father",
    "fatherhood", "fathers", "dads", "dad", "father son", "men of valour",
    "men of valor", "bootcamp", "boot camp", "stag", "bachelor",
    "bachelor party", "ministry to men", "guys night", "boys night",
    "lads", "wild at heart", "band of brothers", "man up", "accountability",
    "accountability group", "discipleship men", "mentoring men",
    "camp for men", "fishing trip", "hunting trip", "golf day", "mens sport",
    "braai night", "cigars and whiskey", "whiskey night", "kingdom men",
    "masculine", "manliness", "men's ministry", "fatherheart",
  ],
  womens: [
    "women", "women's", "womens", "ladies", "ladies night", "ladies lunch",
    "ladies breakfast", "ladies tea", "ladies brunch", "womens conference",
    "ladies conference", "sisterhood", "sisters", "mothers", "motherhood",
    "mums", "moms", "mom", "mum", "mother daughter", "daughters",
    "princess", "pampering", "pamper day", "pamper evening", "high tea",
    "afternoon tea", "tea party", "spa day", "makeup workshop",
    "craft day", "scrapbooking", "craft evening", "book club ladies",
    "ladies book club", "womens bible study", "prayer women",
    "intercessors women", "virtuous woman", "proverbs 31", "esther",
    "ruth", "kingdom woman", "feminine", "womanhood", "single mums",
    "single moms", "baby shower", "bridal shower", "widows",
    "women's ministry", "daughters of the king",
  ],
  kids: [
    "kids", "kids club", "kids church", "children", "children's church",
    "childrens", "childcare", "childminder", "crèche", "creche",
    "nursery", "sunday school", "sabbath school", "bible school", "vbs",
    "vacation bible school", "holiday club", "kids camp", "kidz",
    "kidzone", "kiddies", "toddler", "toddler group", "toddlers",
    "pre-school", "preschool", "play group", "playgroup", "storytime",
    "craft", "kids craft", "kids party", "inflatables", "jumping castle",
    "face painting", "treasure hunt", "puppet show", "puppet ministry",
    "kids worship", "kids praise", "kids dance", "kids drama",
    "kids discipleship", "kids bible", "young disciples", "primary school",
    "infants", "juniors", "mini-church", "children's ministry", "family day",
    "child", "kindergarten",
  ],
  recovery: [
    "recovery", "addiction", "substance abuse", "rehab", "sobriety",
    "sober", "clean and sober", "aa", "alcoholics anonymous", "na",
    "narcotics anonymous", "celebrate recovery", "support group",
    "deliverance", "freedom", "freedom house", "set free", "chains broken",
    "rehabilitation", "detox", "healing journey", "12 step", "twelve step",
    "step study", "inner healing", "trauma healing", "trauma therapy",
    "abuse survivors", "survivor", "porn addiction", "pornography", "lust",
    "sex addiction", "grief", "bereavement", "divorce care",
    "divorce recovery", "single parents", "healing", "healing ministry",
    "restoration", "restore", "ministry of reconciliation",
    "counseling group", "peer support", "sponsor", "fellowship recovery",
    "life change", "testimony", "new life", "born again recovery",
    "beauty for ashes",
  ],
  equip: [
    "equip", "equipping", "training", "training day", "intensive",
    "workshop", "practical training", "practicum", "impartation",
    "activation", "prophetic activation", "healing training",
    "deliverance training", "evangelism training", "discipleship training",
    "leadership training", "leaders meeting", "leaders summit",
    "team training", "staff training", "ministry school",
    "school of ministry", "school of supernatural ministry", "bsm",
    "sozo training", "bethel", "iris", "ywam", "dts",
    "discipleship training school", "servant leadership", "mentoring",
    "mentorship", "coaching", "shadowing", "internship",
    "volunteer training", "usher training", "worship training",
    "worship team training", "musicians training", "tech team training",
    "sound training", "church planting school", "seminary",
    "bible college", "theological training", "elder training",
    "deacon training", "certification", "skill up",
  ],
  weekend: [
    "retreat", "weekend retreat", "conference", "congress", "gathering",
    "weekend", "camp", "encounter", "encounter weekend", "mens weekend",
    "womens weekend", "family weekend", "couples weekend", "youth weekend",
    "summit", "convention", "revival weekend", "revival gathering",
    "kingdom conference", "kingdom weekend", "festival", "fest",
    "campmeeting", "tent meeting", "tent campaign", "kingdom camp",
    "kingdom retreat", "worship conference", "prophetic conference",
    "healing conference", "anointing weekend", "holy spirit weekend",
    "breakthrough weekend", "vision conference", "sabbath weekend",
    "fasting weekend", "silent retreat", "marriage retreat",
    "fathers retreat", "youth camp", "annual gathering",
    "regional gathering", "provincial gathering", "national gathering",
    "pilgrimage", "youth conference", "leaders conference", "glory weekend",
    "revival camp", "refresh", "reset weekend", "vision casting",
  ],
  "members-only": [
    "members", "members only", "members meeting", "congregational meeting",
    "agm", "annual general meeting", "quarterly meeting", "ministry team",
    "leaders meeting", "elders meeting", "deacons meeting",
    "staff meeting", "team meeting", "volunteer meeting",
    "volunteer appreciation", "ministry family", "partners",
    "partners only", "partners event", "partner meeting", "private event",
    "closed", "closed event", "invite only", "invitation only", "internal",
    "internal event", "church family", "church family only", "core team",
    "core", "inner circle", "intercessors meeting", "prayer team",
    "ministry team meeting", "ushers meeting", "worship team meeting",
    "sound team meeting", "production team", "hosts meeting",
    "welcome team", "committee", "committee meeting", "board meeting",
    "council", "elders", "deacons", "trustees", "governance", "members-only",
    "leadership team",
  ],
  care: [
    "care", "counseling", "counselling", "christian counseling",
    "soul care", "soulcare", "pastoral care", "inner healing",
    "healing ministry", "healing room", "healing rooms", "prayer ministry",
    "prayer ministry time", "prayer clinic", "sozo", "theophostic",
    "prophetic ministry time", "freedom ministry", "deliverance",
    "grief share", "grief", "bereavement", "bereavement support",
    "divorce care", "divorce support", "divorced", "single", "singles",
    "widow support", "widow's care", "orphan care", "foster care support",
    "elderly", "elderly care", "visitation", "hospital visit",
    "pastoral visit", "home visit", "care group", "care team",
    "helps ministry", "helps", "mercy ministry", "compassion", "kindness",
    "love walk", "emotional support", "mental health", "depression",
    "anxiety", "burnout", "chaplaincy", "chaplain",
  ],
};
