/**
 * public.profiles column classification (founder decision 2026-09-26,
 * migs 174–177). Shared by the static contract test and the live probe.
 * Changing either list is a privacy decision: it must ship with the
 * migration that grants / revokes the column.
 */
/** Readable by anon + authenticated on ANY row (founder decision 2026-09-26). */
export const PUBLIC_PROFILE_COLUMNS = [
  "id",
  "full_name",
  "role",
  "created_at",
  "avatar_url",
  "bio",
  "handle",
  "handle_changed_at",
  "discoverable",
  "deleted_at",
  "contributor_kind",
  "contributor_status",
  "contributor_slug",
  "contributor_category",
  "contributor_hidden",
  "contributor_no_fixed_location",
  "contributor_contact_email",
  "community_contributor_score",
  "website_url",
  "instagram_handle",
  "facebook_url",
  "tiktok_handle",
  "youtube_url",
  "x_handle",
  "linkedin_url",
  "whatsapp_number",
  "physical_address",
  "physical_latitude",
  "physical_longitude",
  "logo_url",
  "gallery_urls",
  "cover_photo_urls",
  "wear_wardrobe_visibility",
] as const;

/** Own row via get_my_profile_private(); otherwise service_role / SECURITY DEFINER only. */
export const PRIVATE_PROFILE_COLUMNS = [
  "email",
  "notification_email",
  "contributor_claim_email",
  "home_latitude",
  "home_longitude",
  "connect_home_province",
  "gender",
  "age_range",
  "relationship_status",
  "stage_of_life",
  "energy_level",
  "billing_tier",
  "billing_trial_started_at",
  "preferences",
  "notification_prefs",
  "notification_radius_km",
  "notification_digest",
  "muted_source_ids",
  "learn_enrolled_listings",
  "wear_style_preferences",
  "location_sharing",
  "timezone",
  "terms_accepted_at",
  "force_reauth_at",
  "bio_setup_required",
  "needs_re_review",
  "contributor_claimed_at",
  "contributor_created_by_admin",
  // Listing automation consent (mig 181): private, server-owned (set_my_automation_level).
  "auto_update_level",
  "auto_update_consent_at",
  "auto_update_consent_source",
] as const;
